language: java
jdk:
        - oraclejdk9
before_install:
  - wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - mvn -v
script:
        - cd CodingDojo && mvn clean install
cache:
  directories:
  - .autoconf
  - $HOME/.m2
dist: trusty